version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pharmaai-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    # Uncomment if you need to mount volumes
    # volumes:
    #   - .:/app
    #   - /app/node_modules
